### ISSUE TITLE
FizzBuzz conditional could be optimized?

### ISSUE THREAD

**Issue by eliottwiener-thirdchannel** [vanderzee94/codingchallenge#1]
https://github.com/vanderzee94/codingchallenge/blob/46d58561b489ce40f17daf24b41148e99e7e565d/FizzBuzz.java#L16-L24

I have looked over this multi-line conditional, and counted the number of modulo operations that are performed for each of the four cases:

| Divisible by 3 | Divisible by 5 | # of `n % 3 == 0` checks | # of `n % 5 == 0` checks | # of `%` checks total |
|----------------|----------------|----------------|----------------|---------------------|
| yes            | yes            | 1              | 1              | 2                   |
| yes            | no             | 2              | 1              | 3                   |
| no             | yes            | 2              | 1              | 3                   |
| no             | no             | 2              | 1              | 3                   |

---- 

I believe it is possible to reduce the number of checks for some of these cases such that no more than two `%` checks are ever performed. In other words, this:

| Divisible by 3 | Divisible by 5 | # of `n % 3 == 0` checks | # of `n % 5 == 0` checks | # of `%` checks total |
|----------------|----------------|----------------|----------------|---------------------|
| yes            | yes            | 1              | 1              | 2                   |
| yes            | no             | 1              | 1              | 2                   |
| no             | yes            | 1              | 1              | 2                   |
| no             | no             | 1              | 1              | 2                   |

Can you modify your code to reduce the number of checks?

**Comment by vanderzee94** [comment]
https://github.com/vanderzee94/codingchallenge/blob/master/FizzBuzz.java

Updated to use fewer checks. Each modulo is only performed once. I just
implemented the easiest and clearest solutions, not necessarily the
shortest/quickest ones. Let me know if you would like something else.

-Zach
